-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 23:20:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database` ;

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`transactions` ;

CREATE TABLE IF NOT EXISTS `database`.`transactions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `payer_wallets_id` INT UNSIGNED NULL,
  `payee_wallets_id` INT UNSIGNED NOT NULL,
  `enum_transactions_type` VARCHAR(100) NOT NULL COMMENT 'deposit, transfer',
  `enum_currency` VARCHAR(100) NOT NULL COMMENT 'deposit, transfer',
  `amount` DECIMAL(20,2) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_wallets1_idx` (`payer_wallets_id` ASC) VISIBLE,
  INDEX `fk_transactions_wallets2_idx` (`payee_wallets_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_wallets1`
    FOREIGN KEY (`payer_wallets_id`)
    REFERENCES `database`.`wallets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_wallets2`
    FOREIGN KEY (`payee_wallets_id`)
    REFERENCES `database`.`wallets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `database`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`users` ;

CREATE TABLE IF NOT EXISTS `database`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(200) NOT NULL,
  `tax_id` VARCHAR(14) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `enum_users_type` VARCHAR(45) NOT NULL COMMENT 'merchant, customer',
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`tax_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `database`.`wallets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`wallets` ;

CREATE TABLE IF NOT EXISTS `database`.`wallets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `balance` DECIMAL(20,2) NOT NULL,
  `is_primary` TINYBLOB NOT NULL,
  `enum_currency` VARCHAR(10) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wallets_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_wallets_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `database`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
